version: "3"

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: 'meow'
      MYSQL_USER: 'meow'
      MYSQL_PASSWORD: 'meow'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/init.sql

  meow-api:
    image: meow-api:latest
    container_name: meow-api
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

